version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:15
    env_file:
          - ./.env
    volumes:
          - postgres_data:/var/lib/postgresql/data/
    networks:
          - project_network

  django:
      restart: unless-stopped
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
          - ./.env
      volumes:
          - static_volume:/menu-manager-API/static
          - media_volume:/menu-manager-API/media
      networks:
          - project_network
      depends_on:
          - postgres

  nginx:
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./nginx/DockerFile
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d/default.conf
          - static_volume:/menu-manager-API/static
          - media_volume:/menu-manager-API/media
      networks:
          - project_network
      depends_on:
          - django

volumes:
     static_volume:
     media_volume:
     postgres_data:

networks:
    project_network:
    driver: bridge
